Config = Config or {}
Config.PlayerProps = {}
Config.Debug = false -- set true only for local development, allows you to insta build placed house

-- =============================================
-- PLACEMENT SETTINGS
-- =============================================
Config.PromptGroupName          = 'Place House'
Config.FurniturePromptGroupName = 'Place Furniture'
Config.PromptCancelName  = 'Cancel'
Config.PromptPlaceName   = 'Confirm Placement'
Config.PromptRotateLeft  = 'Rotate Left'
Config.PromptRotateRight = 'Rotate Right'
Config.PromptHeightUp    = 'Raise'
Config.PromptHeightDown  = 'Lower'

Config.PlaceDistance      = 50.0   -- max distance from player to place
Config.MinPlotDistance    = 35.0   -- min distance between any two plots
Config.VegetationRadius   = 10.0   -- radius to clear grass around house
Config.PropRenderDistance = 300.0  -- distance to spawn/despawn house props

-- =============================================
-- TAX SETTINGS
-- =============================================
Config.TaxCronJob    = '0 * * * *' -- every hour
Config.TaxGraceDays  = 3           -- days before abandoned flag
Config.AbandonDays   = 7           -- days after grace before repossession

-- =============================================
-- HOUSE PRESETS
-- =============================================
Config.Houses = {

    ['ranch_house'] = {
        label        = 'Wooden House',
        propmodel    = 'free_house01',
        price        = 5000,
        planItem     = 'plan_ranch_house',
        storageSlots  = 80,
        storageWeight = 500000,
        taxPerDay     = 200,

        totalMaterials = {
            { item = 'wood_plank', amount = 500 },
            { item = 'iron_nail',  amount = 400 },
            { item = 'stone',      amount = 300 },
            { item = 'iron_bar',   amount = 120 },
            { item = 'rope',       amount = 120 },
            { item = 'glass_pane', amount = 40  },
        },

        windows = {
            -- All offsets computed from world coords at house heading -140°.
            -- model p_win_njmpl_clean03x
            { model = 'p_win_njmpl_clean03x', offset = { x =  4.245, y = -0.595, z = -1.743, heading =  -0.752 } },
            { model = 'p_win_njmpl_clean03x', offset = { x =  5.827, y =  1.965, z = -1.730, heading =  90.249 } },
            { model = 'p_win_njmpl_clean03x', offset = { x =  5.818, y =  2.905, z = -1.748, heading =  90.249 } },
            { model = 'p_win_njmpl_clean03x', offset = { x =  2.259, y =  4.585, z = -1.730, heading = -179.752 } },
            { model = 'p_win_njmpl_clean03x', offset = { x = -0.623, y =  4.588, z = -1.730, heading = -179.752 } },
            { model = 'p_win_njmpl_clean03x', offset = { x = -3.443, y =  4.604, z = -1.728, heading = -179.752 } },
            { model = 'p_win_njmpl_clean03x', offset = { x = -6.617, y =  2.040, z = -1.730, heading =  -90.753 } },
            { model = 'p_win_njmpl_clean03x', offset = { x = -6.604, y =  1.067, z = -1.756, heading =  -88.753 } },
            { model = 'p_win_njmpl_clean03x', offset = { x = -6.546, y =  1.541, z =  1.363, heading =  -90.753 } },
            { model = 'p_win_njmpl_clean03x', offset = { x = -2.655, y = -4.338, z = -1.730, heading =  -89.753 } },
            { model = 'p_win_njmpl_clean03x', offset = { x = -0.587, y = -7.152, z = -1.744, heading =    1.247 } },
            { model = 'p_win_njmpl_clean03x', offset = { x =  1.208, y = -7.169, z = -1.752, heading =    0.247 } },
        },

        doors = {
            {
                model  = 'p_door04x',
                offset = {
                    -- LOCAL space offsets (relative to model axes at heading=0)
                    -- Computed by un-rotating world offsets (0.4361, -3.4296)
                    -- measured at house heading -34.236° in spooner
                    x       =  2.2879,
                    y       = -2.5917,
                    z       = -2.6200,
                    heading = -90.0,
                },
            },
            {
                model  = 'p_door09x',
                offset = {
                    -- LOCAL space offsets computed from spooner data:
                    -- Door world pos (-1605.0726, 338.2198, 104.0330), rotZ -179.946
                    -- House world pos (-1610.2861, 337.7508, 106.6561), rotZ -180.000
                    -- World delta rotated into local space at heading 180°
                    x       = -5.2135,
                    y       = -0.4690,
                    z       = -2.6231,
                    heading =  0.0,
                },
            },
        },

    },
}

-- =============================================
-- HOUSING AGENT NPC LOCATIONS
-- Update coords after testing on server
-- =============================================
Config.HousingAgents = {
    {
        label  = 'Valentine Housing Agent',
        coords = vector4(-345.2200012207031, 797.0700073242188, 116.1496810913086, 98.34),
        model  = `A_M_M_ValFarmer_01`,
    },
}

-- =============================================
-- FURNITURE SETTINGS
-- =============================================
Config.FurniturePlacementRadius = 20.0   -- max distance from plot center to place furniture
Config.FurniturePreviewDuration = 5000  -- ms the in-world preview ghost is shown before auto-delete

Config.FurnitureCategories = {
    {
        label = 'Tables',
        icon  = 'fa-solid fa-table',
        props = {
            { model = 'p_table01x',              price = 450 },
            { model = 'p_table02x',              price = 150 },
            { model = 'p_table10x',              price = 150 },
            { model = 'p_table11x',              price = 150 },
            { model = 'p_table14x',              price = 150 },
            { model = 'p_table31x',              price = 150 },
            { model = 'p_table32x',              price = 150 },
            { model = 'p_table38x',              price = 150 },
            { model = 'p_table41x',              price = 150 },
            { model = 'p_table42_cs',            price = 150 },
            { model = 'p_table44x',              price = 150 },
            { model = 'p_table46x',              price = 150 },
            { model = 'p_table50x',              price = 150 },
            { model = 'p_table51x',              price = 150 },
            { model = 'p_tabledining03xb',       price = 150 },
            { model = 'p_tableprep01x',          price = 150 },
            { model = 'p_tablebedside01x',       price = 150 },
            { model = 'p_tablebedside02x',       price = 150 },
            { model = 'p_grp_w_tra_sidetable01x', price = 150 },
            { model = 'p_tablework02x',          price = 150 },
            { model = 'p_tableconsole01x',       price = 150 },
            { model = 'p_tableconsole02x',       price = 150 },
            { model = 'p_tableconsole03bx',      price = 150 },
            { model = 'p_tableconsole03x',       price = 150 },
            { model = 'p_tableconsole04x',       price = 150 },
            { model = 'p_tableconsole05bx',      price = 150 },
            { model = 'p_tablegiltconsole01x',   price = 150 },
            { model = 'p_tablegiltwood01x',      price = 150 },
        },
    },
    {
        label = 'Chairs',
        icon  = 'fa-solid fa-chair',
        props = {
            { model = 'p_chair02x',           price = 100 },
            { model = 'p_chair04x',           price = 100 },
            { model = 'p_chair05x',           price = 100 },
            { model = 'p_chair06x',           price = 100 },
            { model = 'p_chair09x',           price = 100 },
            { model = 'p_chair15x',           price = 100 },
            { model = 'p_chair17x',           price = 100 },
            { model = 'p_chair18x',           price = 100 },
            { model = 'p_chair19x',           price = 100 },
            { model = 'p_chair22x',           price = 100 },
            { model = 'p_chair34x',           price = 100 },
            { model = 'p_chair37x',           price = 100 },
            { model = 'p_chaircomfy01x',      price = 100 },
            { model = 'p_chaircomfy02',       price = 100 },
            { model = 'p_chaircomfy03x',      price = 100 },
            { model = 'p_chaircomfy04x',      price = 100 },
            { model = 'p_chaircomfy07x',      price = 100 },
            { model = 'p_chaircomfy12x',      price = 100 },
            { model = 'p_chaircomfy14x',      price = 100 },
            { model = 'p_chairdesk01x',       price = 100 },
            { model = 'p_chairdesk02x',       price = 100 },
            { model = 'p_chairpokerfancy01x', price = 100 },
            { model = 'p_woodendeskchair01x', price = 100 },
        },
    },
    {
        label = 'Plants (Indoor)',
        icon  = 'fa-solid fa-seedling',
        props = {
            { model = 'p_plant_moneytree',       price = 50 },
            { model = 'p_exoticprops14x',        price = 50 },
            { model = 'p_plantpotnbx05x',        price = 50 },
            { model = 'p_plantpotnbx06x',        price = 50 },
            { model = 'p_plantpotnbx07x',        price = 50 },
            { model = 'p_plantpothangnbx01x',    price = 50 },
            { model = 'p_pot_flowerarng02x',     price = 50 },
            { model = 'p_pot_flowerarng03x',     price = 50 },
            { model = 'p_pot_flowerarng05x',     price = 50 },
            { model = 'p_pot_flowerarng07x',     price = 50 },
            { model = 'p_pot_flowerarng08x',     price = 50 },
            { model = 'p_pot_flowerarng09bx',    price = 50 },
            { model = 'p_pot_flowerarng16x',     price = 50 },
            { model = 'p_pot_flowerarng17x',     price = 50 },
            { model = 'p_pot_flowerarng18x',     price = 50 },
            { model = 'p_pot_flowerarng23x',     price = 50 },
            { model = 'p_pot_flowerarngdead02',  price = 50 },
            { model = 'p_pot_leafyvase',         price = 50 },
            { model = 'p_pot_plant_05a',         price = 50 },
            { model = 'p_pot_plant_05b',         price = 50 },
            { model = 'p_pot_plant_6a',          price = 50 },
            { model = 'p_pot_plant_6b',          price = 50 },
            { model = 'p_pot_plant_08a',         price = 50 },
            { model = 'p_group_flowertable01',   price = 50 },
            { model = 'p_plant_philo',           price = 50 },
            { model = 'p_plant_philo2',          price = 50 },
            { model = 'p_plant05x',              price = 50 },
            { model = 'p_plant06x',              price = 50 },
            { model = 'p_planter',               price = 50 },
            { model = 'p_planter03a',            price = 50 },
            { model = 'p_planter03x',            price = 50 },
            { model = 'p_planternbx04a',         price = 50 },
            { model = 'p_planternbx04b',         price = 50 },
        },
    },
    {
        label = 'Lights',
        icon  = 'fa-solid fa-lightbulb',
        props = {
            { model = 'p_candle01x',           price = 75 },
            { model = 'p_candlebot01x',        price = 75 },
            { model = 'p_candlestand',         price = 75 },
            { model = 'p_candlegroup05x',      price = 75 },
            { model = 'p_lanternhang01x',      price = 75 },
            { model = 'p_lantern08x',          price = 75 },
            { model = 'p_walllampnbx02x',      price = 75 },
            { model = 'p_gnomeoillamp01x',     price = 75 },
            { model = 'p_chandelier14x',       price = 75 },
            { model = 'p_lamp17x',             price = 75 },
            { model = 'p_lamp30x',             price = 75 },
            { model = 'p_lampbar01x',          price = 75 },
            { model = 'p_lamphanging03x',      price = 75 },
            { model = 'p_lamphanging07x',      price = 75 },
            { model = 'p_lamphangnbx01x',      price = 75 },
            { model = 'p_lamphanging08x',      price = 75 },
            { model = 'p_lantern04xlowfuel',   price = 75 },
            { model = 'p_lantern05x',          price = 75 },
            { model = 'p_lampstanding03x',     price = 75 },
            { model = 'p_lampstanding04x',     price = 75 },
            { model = 'p_lampstanding07x',     price = 75 },
            { model = 'p_lampstanding09x',     price = 75 },
            { model = 'p_medlight02x',         price = 75 },
            { model = 'p_kerosenetablelamp01x', price = 75 },
            { model = 'p_lamp27x',             price = 75 },
            { model = 'p_lamp32x',             price = 75 },
            { model = 'p_lamp33x',             price = 75 },
            { model = 'p_lanternbrass02x',     price = 75 },
            { model = 'p_kerosenewalllamp01x', price = 75 },
            { model = 'p_lamp01x',             price = 75 },
            { model = 'p_lampwall02x',         price = 75 },
            { model = 'p_lampwall04x',         price = 75 },
            { model = 'p_lampwall07x',         price = 75 },
            { model = 'p_lampwall12x',         price = 75 },
            { model = 'p_sconcelight01x',      price = 75 },
        },
    },
    {
        label = 'Bathroom',
        icon  = 'fa-solid fa-bath',
        props = {
            { model = 'p_bath02bx',              price = 120 },
            { model = 'p_bath02x',               price = 120 },
            { model = 'p_bath03x',               price = 120 },
            { model = 'p_bathsponge01x',         price = 120 },
            { model = 'p_comb01x',               price = 120 },
            { model = 'p_shavingboxclosed01x',   price = 120 },
            { model = 'p_tub01bx',               price = 120 },
            { model = 'p_tub02x',                price = 120 },
            { model = 'p_val_hotel_int_tub_01x', price = 120 },
            { model = 'p_washstand02x_static',   price = 120 },
            { model = 'p_bathbrush01x',          price = 120 },
            { model = 'p_bedpanladies01x',       price = 120 },
            { model = 'p_cupboard07x',           price = 120 },
            { model = 'p_shaving_set01x',        price = 120 },
            { model = 'p_shavingbox01x',         price = 120 },
            { model = 'p_shavingbrush01x',       price = 120 },
            { model = 'p_shavingcup01x',         price = 120 },
            { model = 'p_soap01x',               price = 120 },
            { model = 'p_straightrazor01x',      price = 120 },
            { model = 'p_towelrack01x',          price = 120 },
            { model = 'p_washbasin01x',          price = 120 },
            { model = 'p_washbasinregal01x',     price = 120 },
            { model = 'p_washbasinset01ax',      price = 120 },
            { model = 'p_washbasinset01bx',      price = 120 },
            { model = 'p_washbasinset01x',       price = 120 },
            { model = 'p_washboard_01',          price = 120 },
            { model = 'p_washstand02x',          price = 120 },
            { model = 'p_washstand03x',          price = 120 },
        },
    },
    {
        label = 'Bedroom',
        icon  = 'fa-solid fa-bed',
        props = {
            { model = 'p_bed_abigail3x',      price = 200 },
            { model = 'p_bed01x',             price = 200 },
            { model = 'p_bed02bx',            price = 200 },
            { model = 'p_bed02x',             price = 200 },
            { model = 'p_bed04x',             price = 200 },
            { model = 'p_bed08x',             price = 200 },
            { model = 'p_bed09x',             price = 200 },
            { model = 'p_bed12x',             price = 200 },
            { model = 'p_bed15brassx',        price = 200 },
            { model = 'p_bed18x',             price = 200 },
            { model = 'p_bed03x',             price = 200 },
            { model = 'p_bed05x',             price = 200 },
            { model = 'p_bed10x',             price = 200 },
            { model = 'p_bed13x',             price = 200 },
            { model = 'p_bed14x',             price = 200 },
            { model = 'p_bed17x',             price = 200 },
            { model = 'p_bed20madex',         price = 200 },
            { model = 'p_bed20x',             price = 200 },
            { model = 'p_bed21x',             price = 200 },
            { model = 'p_bed22x',             price = 200 },
            { model = 'p_bed20bloodyx',       price = 200 },
            { model = 'p_bedindian01x',       price = 200 },
            { model = 'p_bedking01x',         price = 200 },
            { model = 'p_bedlog01x',          price = 200 },
            { model = 'p_bedmosquitonet01x',  price = 200 },
            { model = 'p_bedsleptin01x',      price = 200 },
            { model = 'p_bedsleptinold04x',   price = 200 },
            { model = 'p_blanketfolded01x',   price = 200 },
            { model = 'p_chamberpot_pot',     price = 200 },
            { model = 'p_clothingcase01x',    price = 200 },
            { model = 'p_cradle01x',          price = 200 },
            { model = 'p_dresser08x',         price = 200 },
            { model = 'p_dressmirror01x',     price = 200 },
            { model = 'p_foldedrug01x',       price = 200 },
            { model = 'p_footlocker01x',      price = 200 },
            { model = 'p_footlockeranim01x',  price = 200 },
            { model = 'p_mattress03x',        price = 200 },
            { model = 'p_mattress07x',        price = 200 },
            { model = 'p_mattress08x',        price = 200 },
            { model = 'p_nightbedking01x',    price = 200 },
            { model = 'p_nightstand04x',      price = 200 },
            { model = 'p_singlebrassbed01x',  price = 200 },
            { model = 'p_alarmclock01x',      price = 200 },
            { model = 'p_armoir02x_loot',     price = 200 },
            { model = 'p_armoir02x',          price = 200 },
            { model = 'p_armoir03x',          price = 200 },
            { model = 'p_armoir04x_loot',     price = 200 },
            { model = 'p_armoir04x',          price = 200 },
            { model = 'p_armoir05x_loot',     price = 200 },
            { model = 'p_armoir05x',          price = 200 },
            { model = 'p_armoir06x',          price = 200 },
            { model = 'p_armoir07bx',         price = 200 },
            { model = 'p_armoir07x_loot',     price = 200 },
            { model = 'p_armoir07x',          price = 200 },
            { model = 'p_armoir08x',          price = 200 },
            { model = 'p_armoireregal01',     price = 200 },
            { model = 'p_bedbunk03x',         price = 200 },
            { model = 'p_bedking02x',         price = 200 },
            { model = 'p_cabinet03x',         price = 200 },
            { model = 'p_cabinet04x',         price = 200 },
            { model = 'p_cabinet05x',         price = 200 },
            { model = 'p_chamberpot01x',      price = 200 },
            { model = 'p_chest01x',           price = 200 },
            { model = 'p_chest02x',           price = 200 },
            { model = 'p_chest03x',           price = 200 },
            { model = 'p_commode01x',         price = 200 },
            { model = 'p_commode02x',         price = 200 },
            { model = 'p_dresser01x',         price = 200 },
            { model = 'p_dresser03x',         price = 200 },
            { model = 'p_dresser04x',         price = 200 },
            { model = 'p_dresser05x',         price = 200 },
            { model = 'p_dresser06x',         price = 200 },
            { model = 'p_dresser07x',         price = 200 },
            { model = 'p_dresser09x',         price = 200 },
            { model = 'p_dresserval01x',      price = 200 },
            { model = 'p_foldedblanket01x',   price = 200 },
            { model = 'p_foldedblanket02x',   price = 200 },
            { model = 'p_footlocker07x_loot', price = 200 },
            { model = 'p_footlocker07x',      price = 200 },
            { model = 'p_lacepillow01x',      price = 200 },
            { model = 'p_lacepillow02x',      price = 200 },
            { model = 'p_mattress04x',        price = 200 },
            { model = 'p_mirror_shave01x',    price = 200 },
            { model = 'p_nightstand03x',      price = 200 },
            { model = 'p_nightstandwinter03x', price = 200 },
            { model = 'p_pillow01x_sea',      price = 200 },
            { model = 'p_pillow01x',          price = 200 },
            { model = 'p_pillow02x',          price = 200 },
            { model = 'p_pillow03x',          price = 200 },
            { model = 'p_pillow06x',          price = 200 },
            { model = 'p_pillow08x',          price = 200 },
            { model = 'p_pillow09x',          price = 200 },
            { model = 'p_pillow10x',          price = 200 },
            { model = 'p_pillow11x',          price = 200 },
            { model = 'p_pillow12x',          price = 200 },
            { model = 'p_steamer_trunk_001',  price = 200 },
            { model = 'p_vanity01x',          price = 200 },
            { model = 'p_vanity02x',          price = 200 },
        },
    },
    {
        label = 'Living Room',
        icon  = 'fa-solid fa-couch',
        props = {
            { model = 'p_seatbench01x',          price = 175 },
            { model = 'p_sit_chairwicker01a',    price = 175 },
            { model = 'p_couchwicker01x',        price = 175 },
            { model = 'p_trunkvar01x_noloot',    price = 175 },
            { model = 'p_weddingchest01x',       price = 175 },
            { model = 's_footlocker01x',         price = 175 },
            { model = 'p_couch06x',              price = 175 },
            { model = 'p_couch08x',              price = 175 },
            { model = 'p_couch10x',              price = 175 },
            { model = 'p_loveseat01x',           price = 175 },
            { model = 'p_settee_05x',            price = 175 },
            { model = 'p_settee02bx',            price = 175 },
            { model = 'p_settee02x',             price = 175 },
            { model = 'p_sofa01x',               price = 175 },
            { model = 'p_victoriansofa01x',      price = 175 },
            { model = 'p_armoiroffice66x',       price = 175 },
            { model = 'p_buffet01x',             price = 175 },
            { model = 'p_cabinetdoctor01x',      price = 175 },
            { model = 'p_shelf06x',              price = 175 },
            { model = 'p_bw_desk01x',            price = 175 },
            { model = 'p_desk01x',               price = 175 },
            { model = 'p_desk03x',               price = 175 },
            { model = 'p_desk04x',               price = 175 },
            { model = 'p_desk10x',               price = 175 },
            { model = 'p_desk13x',               price = 175 },
            { model = 'p_drdesk01x',             price = 175 },
            { model = 'p_trolleymaildesk_01x',   price = 175 },
            { model = 'p_vanitydresserdesk01x',  price = 175 },
            { model = 'p_coatstand01x',          price = 175 },
            { model = 'p_doc_coatstandrack01x',  price = 175 },
            { model = 'p_gun_hangitem02x',        price = 175 },
            { model = 'p_gunsmithprops16x',      price = 175 },
            { model = 'p_hatstandbear01x',       price = 175 },
        },
    },
    {
        label = 'Indoor Decor',
        icon  = 'fa-solid fa-paint-brush',
        props = {
            { model = 'p_books01x',                   price = 60 },
            { model = 'p_books02x',                   price = 60 },
            { model = 'p_bookset04x',                 price = 60 },
            { model = 'p_bookset05x',                 price = 60 },
            { model = 'p_book04x',                    price = 60 },
            { model = 'p_book05x',                    price = 60 },
            { model = 'p_book06x',                    price = 60 },
            { model = 'p_jug01bx',                    price = 60 },
            { model = 'p_bottlebeer01a',              price = 60 },
            { model = 'p_grp_new_sal02_props04x',     price = 60 },
            { model = 'p_boxlrgcotton01x',            price = 60 },
            { model = 'p_boxlrgleather01x',           price = 60 },
            { model = 'p_boxmeddeposit01x',           price = 60 },
            { model = 'p_boxmedpaint01x',             price = 60 },
            { model = 'p_boxmedsuitcase01x',          price = 60 },
            { model = 'p_boxsmljewelery01x',          price = 60 },
            { model = 'p_sto_buysellbox02x',          price = 60 },
            { model = 's_saddiessupply01x',           price = 60 },
            { model = 'p_basket05x',                  price = 60 },
            { model = 'p_basket06x',                  price = 60 },
            { model = 'p_basket13x',                  price = 60 },
            { model = 'p_baskethalf01x',              price = 60 },
            { model = 'p_bag01x',                     price = 60 },
            { model = 'p_baghang02x',                 price = 60 },
            { model = 'p_cs_suitcase01x',             price = 60 },
            { model = 's_pistolchest_loot',           price = 60 },
            { model = 'p_scalecandy01x',              price = 60 },
            { model = 'p_basket06cx',                 price = 60 },
            { model = 'p_piestand01x',                price = 60 },
            { model = 'p_knifeblock03x',              price = 60 },
            { model = 'p_valbankclock01x',            price = 60 },
            { model = 'p_clock06x',                   price = 60 },
            { model = 'p_mantle_clock_old',           price = 60 },
            { model = 'p_deskstand01x',               price = 60 },
            { model = 'p_deskorganizer01x',           price = 60 },
            { model = 'p_fandesk_off01x',             price = 60 },
            { model = 'p_letterbox_01x',              price = 60 },
            { model = 'mp007_p_nat_pictureframe01x',  price = 60 },
            { model = 'mp007_p_nat_pictureframe02x',  price = 60 },
            { model = 'mp007_p_nat_pictureframe03x',  price = 60 },
            { model = 'mp007_p_nat_pictureframe04x',  price = 60 },
            { model = 'p_flowerframe01x',             price = 60 },
            { model = 'p_painting_newgala_sml01x',    price = 60 },
            { model = 'p_picturemirror02x',           price = 60 },
            { model = 'mp006_p_mshn_painting01x',     price = 60 },
            { model = 'mp006_p_mshn_painting02x',     price = 60 },
            { model = 'mp006_p_mshn_painting03x',     price = 60 },
            { model = 'mp006_p_mshn_painting04x',     price = 60 },
            { model = 'mp006_p_mshn_painting05x',     price = 60 },
            { model = 'mp006_p_mshn_painting06x',     price = 60 },
            { model = 'mp006_p_mshn_painting07x',     price = 60 },
            { model = 'mp006_p_mshn_painting08x',     price = 60 },
            { model = 'mp006_p_mshn_painting09x',     price = 60 },
            { model = 'mp006_p_mshn_painting10x',     price = 60 },
            { model = 'p_cs_photowolves',             price = 60 },
            { model = 'mp006_p_bowl_apple01x',        price = 60 },
            { model = 'mp006_p_bowl_banana01x',       price = 60 },
            { model = 'p_gourdsbundle01x',            price = 60 },
            { model = 'p_stewplate01x',               price = 60 },
            { model = 'p_tutlesoup01x',               price = 60 },
            { model = 'p_sink02x',                    price = 60 },
            { model = 'p_sink04x',                    price = 60 },
            { model = 'p_drysink01x',                 price = 60 },
            { model = 'p_pedestal01x',                price = 60 },
            { model = 'p_counterdoctor01x',           price = 60 },
        },
    },
    {
        label = 'Outdoor Decor',
        icon  = 'fa-solid fa-tree',
        props = {
            { model = 'p_hitchingpost01x',       price = 80 },
            { model = 'p_hitchingpost05x',       price = 80 },
            { model = 'p_bra_cal_sgn_tress2a',   price = 80 },
            { model = 'p_scarecrow01x',          price = 80 },
            { model = 'p_chickencoopcart01x',    price = 80 },
            { model = 'p_bucketpigfeed02x',      price = 80 },
            { model = 'p_outhouse03x',           price = 80 },
            { model = 'p_bench03x',              price = 80 },
            { model = 'p_bench09x',              price = 80 },
            { model = 'p_bespoketable01x',       price = 80 },
            { model = 'p_sawbucktable01x',       price = 80 },
            { model = 'p_tablesur01x',           price = 80 },
            { model = 'p_tableset01x',           price = 80 },
            { model = 'p_haybale01x',            price = 80 },
            { model = 'p_haybalecover01x',       price = 80 },
            { model = 'p_haycartcover01x',       price = 80 },
            { model = 'p_haypile01x',            price = 80 },
            { model = 'p_haypile04x',            price = 80 },
            { model = 'p_harness04x',            price = 80 },
            { model = 'p_jumphurdles01x',        price = 80 },
            { model = 'p_grp_sdlstand01x_car_sd', price = 80 },
            { model = 'p_feedtroughsml01x',      price = 80 },
        },
    },
    {
        label = 'Plants (Outdoor)',
        icon  = 'fa-solid fa-leaf',
        props = {
            { model = 's_inv_bloodflower_bunch01x',  price = 40 },
            { model = 'engmace_p',                   price = 40 },
            { model = 'prariepoppy_p',               price = 40 },
            { model = 's_violetsnowdrop01x',         price = 40 },
            { model = 'viosnwdrp_p',                 price = 40 },
            { model = 's_inv_blackberry01x',         price = 40 },
            { model = 'oregano_p',                   price = 40 },
            { model = 'milkweed_p',                  price = 40 },
            { model = 'p_ambfloorleaves01x',         price = 40 },
            { model = 'p_ambfloorleaves02x',         price = 40 },
            { model = 'rdr_bush_hedgecore_aa',       price = 40 },
            { model = 'rdr_bush_fern_ab_sim',        price = 40 },
            { model = 'rdr_bush_neat_ba_sim',        price = 40 },
            { model = 'rdr_bush_neat_bc_sim',        price = 40 },
            { model = 'rdr_bush_neat_ae_sim',        price = 40 },
            { model = 'rdr_bush_paradise_aa_sim',    price = 40 },
            { model = 'p_tree_cedar_decor_02',       price = 40 },
            { model = 'rdr_bush_neat_ab_sim',        price = 40 },
            { model = 'rdr_bush_wandering_aa_sim',   price = 40 },
            { model = 'rdr_bush_soga_aa_sim',        price = 40 },
        },
    },
    {
        label = 'Camp',
        icon  = 'fa-solid fa-campground',
        props = {
            { model = 'p_ambcloth03x',                price = 90 },
            { model = 'p_bandage01x',                 price = 90 },
            { model = 'p_bandage02x',                 price = 90 },
            { model = 'p_bandage03x',                 price = 90 },
            { model = 'p_bedrollopen01x',             price = 90 },
            { model = 'p_bedrollopen03x',             price = 90 },
            { model = 'p_boilercamp01x',              price = 90 },
            { model = 'p_campfire_06x',               price = 90 },
            { model = 'p_campfire_coloursmoke01x',    price = 90 },
            { model = 'p_campfire_under01x',          price = 90 },
            { model = 'p_campfire_win2_01x',          price = 90 },
            { model = 'p_campfire_win2_smolder01x',   price = 90 },
            { model = 'p_campfire01x_nofire',         price = 90 },
            { model = 'p_campfire01x',                price = 90 },
            { model = 'p_campfire02_amb',             price = 90 },
            { model = 'p_campfire02x_script',         price = 90 },
            { model = 'p_campfire02x',                price = 90 },
            { model = 'p_campfire02xb',               price = 90 },
            { model = 'p_campfire03x_nofire',         price = 90 },
            { model = 'p_campfire03x',                price = 90 },
            { model = 'p_campfire04x',                price = 90 },
            { model = 'p_campfire05x_script',         price = 90 },
            { model = 'p_campfire05x',                price = 90 },
            { model = 'p_campfirebasin01x',           price = 90 },
            { model = 'p_campfireburnedout05x',       price = 90 },
            { model = 'p_campfireburntout02x',        price = 90 },
            { model = 'p_campfirechar01x',            price = 90 },
            { model = 'p_campfirecharsml01x',         price = 90 },
            { model = 'p_campfirecombined01x_off',    price = 90 },
            { model = 'p_campfirecook01x',            price = 90 },
            { model = 'p_campfirecook02x',            price = 90 },
            { model = 'p_campfiredebris01x',          price = 90 },
            { model = 'p_campfiredirt01x',            price = 90 },
            { model = 'p_campfiredirt01x002',         price = 90 },
            { model = 'p_campfiredirtsml01x',         price = 90 },
            { model = 'p_campfireembers01x',          price = 90 },
            { model = 'p_campfirefresh01x',           price = 90 },
            { model = 'p_campfirenosmoke01x',         price = 90 },
            { model = 'p_campfirerock01x',            price = 90 },
            { model = 'p_campfirerock02x',            price = 90 },
            { model = 'p_campfirerocksml01x',         price = 90 },
            { model = 'p_campfirerocksml02x',         price = 90 },
            { model = 'p_campfiresmlsmolder01x',      price = 90 },
            { model = 'p_campfiresmolder01x',         price = 90 },
            { model = 'p_campfiretemplate01x',        price = 90 },
            { model = 'p_campfirewhitefish03x',       price = 90 },
            { model = 'p_canopy66x',                  price = 90 },
            { model = 'p_compass01x',                 price = 90 },
            { model = 'p_cookgrate01x',               price = 90 },
            { model = 'p_cookgrate02x',               price = 90 },
            { model = 'p_cot01x',                     price = 90 },
            { model = 'p_coverboar01x',               price = 90 },
            { model = 'p_coverpronghorn01x',          price = 90 },
            { model = 'p_coverpronghorn02x',          price = 90 },
            { model = 'p_craftingpot01x',             price = 90 },
            { model = 'p_firebarrel01x',              price = 90 },
            { model = 'p_firesignal01x',              price = 90 },
            { model = 'p_leantopine01x',              price = 90 },
            { model = 'p_map01x',                     price = 90 },
            { model = 'p_map02x',                     price = 90 },
            { model = 'p_map03x',                     price = 90 },
            { model = 'p_matchstick01x_pickup',       price = 90 },
            { model = 'p_prisoncage02x',              price = 90 },
            { model = 'p_stake01x',                   price = 90 },
            { model = 'p_stick01x',                   price = 90 },
            { model = 'p_stick02x',                   price = 90 },
            { model = 'p_stick03x',                   price = 90 },
            { model = 'p_stick04x',                   price = 90 },
            { model = 'p_stickfirepoker01x',          price = 90 },
            { model = 'p_stump_01bx',                 price = 90 },
            { model = 'p_stump_01x',                  price = 90 },
            { model = 'p_stump',                      price = 90 },
            { model = 'p_stumpwoodsplit01x',          price = 90 },
            { model = 'p_stumpwoodsplit02x',          price = 90 },
            { model = 'p_tentarmypupbroken02x',       price = 90 },
            { model = 'p_tentarmypupbroken04x',       price = 90 },
            { model = 'p_tentrack01x',                price = 90 },
            { model = 'p_tentrolled01x',              price = 90 },
            { model = 'p_tentrolled02x',              price = 90 },
            { model = 'p_amb_tent01x',                price = 90 },
            { model = 'p_amb_tent02x',                price = 90 },
            { model = 'p_amb_tent03x',                price = 90 },
            { model = 'p_bedrollclosed_sml01x',       price = 90 },
            { model = 'p_bedrollclosed_sml02x',       price = 90 },
            { model = 'p_bedrollclosed01x',           price = 90 },
            { model = 'p_bedrollclosed03x',           price = 90 },
            { model = 'p_camp_cup_01x',               price = 90 },
            { model = 'p_camp_plate_01x',             price = 90 },
            { model = 'p_camp_plate_02x',             price = 90 },
            { model = 'p_camp_plate_03x',             price = 90 },
            { model = 'p_campfire02x_combo',          price = 90 },
            { model = 'p_campfire02x_dynamic',        price = 90 },
            { model = 'p_campfirecombined01x',        price = 90 },
            { model = 'p_campfirecombined02x',        price = 90 },
            { model = 'p_campfirecombined03x',        price = 90 },
            { model = 'p_campfirecombined04x',        price = 90 },
            { model = 'p_campfireprop02x',            price = 90 },
            { model = 'p_canopycloth',                price = 90 },
            { model = 'p_canopycloth03x',             price = 90 },
            { model = 'p_clothesline01x',             price = 90 },
            { model = 'p_cookfirestructure02x',       price = 90 },
            { model = 'p_firesticks01x',              price = 90 },
            { model = 'p_kindlingpile01x',            price = 90 },
            { model = 'p_leanto02x',                  price = 90 },
            { model = 'p_leanto03x',                  price = 90 },
            { model = 'p_matches01x',                 price = 90 },
            { model = 'p_matchstick01x',              price = 90 },
            { model = 'p_platedog01x',                price = 90 },
            { model = 'p_prisoncage01x',              price = 90 },
            { model = 'p_tarp01x',                    price = 90 },
            { model = 'p_tarp04x',                    price = 90 },
            { model = 'p_tarpbutcher01x',             price = 90 },
            { model = 'p_tent_leento01x',             price = 90 },
            { model = 'p_tent_leento02x',             price = 90 },
            { model = 'p_tent_leento03x',             price = 90 },
            { model = 'p_tent_leento04x',             price = 90 },
            { model = 'p_tent0101x',                  price = 90 },
            { model = 'p_tentarmypup01bx',            price = 90 },
            { model = 'p_tentarmypup01x',             price = 90 },
            { model = 'p_tentarmypup02x_open',        price = 90 },
            { model = 'p_tentarmypup02x',             price = 90 },
            { model = 'p_tentarmypupbroken01x',       price = 90 },
            { model = 'p_tentarmypupbroken03x',       price = 90 },
            { model = 'p_tentarmypupbrokensnow01x',   price = 90 },
            { model = 'p_tentdamaged02x',             price = 90 },
            { model = 'p_tentmexican01x',             price = 90 },
            { model = 'p_tentmountainmen01x',         price = 90 },
            { model = 'p_tentmountainmen02x',         price = 90 },
            { model = 'p_tentnorth01bx',              price = 90 },
            { model = 'p_tentnorth01x',               price = 90 },
            { model = 'p_tentplain01x',               price = 90 },
            { model = 'p_tentrack02x',                price = 90 },
            { model = 'p_tentrolled04x',              price = 90 },
            { model = 'p_tentstripebroken01x',        price = 90 },
        },
    },
    {
        label = 'Barrier',
        icon  = 'fa-solid fa-border-all',
        props = {
            { model = 'p_barricadewood_sml01x',  price = 100 },
            { model = 'p_avoidancebound01x',     price = 100 },
            { model = 'p_barricade01x',          price = 100 },
            { model = 'p_barricade03x',          price = 100 },
            { model = 'p_barricade04x',          price = 100 },
            { model = 'p_barricade05x',          price = 100 },
            { model = 'p_barricadewood_lrg01x',  price = 100 },
            { model = 'p_concretesack01x',       price = 100 },
            { model = 'p_bra_fence01x',          price = 100 },
            { model = 'p_bra_fence03x',          price = 100 },
            { model = 'p_bra_fencepost01x',      price = 100 },
            { model = 'p_chickenfence01x',       price = 100 },
            { model = 'p_chickenfencepost',      price = 100 },
            { model = 'p_emrfence02bx',          price = 100 },
            { model = 'p_emrfence03cx',          price = 100 },
            { model = 'p_fence01ax',             price = 100 },
            { model = 'p_fence01bx',             price = 100 },
            { model = 'p_fence01cx',             price = 100 },
            { model = 'p_fence01dx',             price = 100 },
            { model = 'p_fence02cx',             price = 100 },
            { model = 'p_fence02x',              price = 100 },
            { model = 'p_fence04ax',             price = 100 },
            { model = 'p_fence04bx',             price = 100 },
            { model = 'p_fence06ax',             price = 100 },
            { model = 'p_fence06bx',             price = 100 },
        },
    },
}

-- =============================================
-- MAP BLIP SETTINGS
-- =============================================
Config.Blip = {
    ownBlipName       = 'My Property',
    guestBlipName     = 'Friend\'s Property',
    otherBlipName     = 'Player Property',
    abandonedBlipName = 'Abandoned Property',
    ownBlipSprite     = 'blip_event_castor',          -- hash: -1989725258
    otherBlipSprite   = 'blip_event_castor',
    blipScale         = 0.25,
    ownColour         = 'BLIP_MODIFIER_MP_COLOR_8',   -- green 
    guestColour       = 'BLIP_MODIFIER_MP_COLOR_8',   -- green
    otherColour       = nil,                          -- nil = no modifier = default sprite colour (grey)
    abandonedColour   = 'BLIP_MODIFIER_MP_COLOR_2',   -- red = abandoned/danger
    agentBlipSprite   = 'blip_ambient_quartermaster',  -- hash: 249721687
    agentBlipColour   = 'BLIP_MODIFIER_MP_COLOR_8',   -- green
}
